version: '3.3'

networks:
  traefik_net:
    external: true

services:
  nginx:
    build: .
    ports:
      - 1935:1935
      # - 8080:80

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.hls-backchannel-hmnd-de.entrypoints=http
      - traefik.http.routers.hls-backchannel-hmnd-de.rule=Host("hls.backchannel.hmnd.de")
      - traefik.http.middlewares.hls-backchannel-hmnd-de-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.hls-backchannel-hmnd-de.middlewares=hls-backchannel-hmnd-de-https-redirect
      - traefik.http.routers.hls-backchannel-hmnd-de-secure.entrypoints=https
      - traefik.http.routers.hls-backchannel-hmnd-de-secure.rule=Host("hls.backchannel.hmnd.de")
      - traefik.http.routers.hls-backchannel-hmnd-de-secure.tls=true
      - traefik.http.routers.hls-backchannel-hmnd-de-secure.tls.certresolver=http
      - traefik.http.routers.hls-backchannel-hmnd-de-secure.service=hls-backchannel-hmnd-de
      - traefik.http.services.hls-backchannel-hmnd-de.loadbalancer.server.port=80